### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by Eugene-Mokrushin** [jmalku/amzn_fetch#1]
Hello! 
I'm not very savvy in python. Can you explain me what I did wrong here?
```
PS C:\*\parse-amazon> py .\parseAM.py
Getting page: 1 | https://www.amazon.com/s?k=dog collar&page=1
Traceback (most recent call last):
  File "C:\*\parseAM.py", line 168, in <module>
    search_keyword('dog collar')
  File "C:\*\parseAM.py", line 142, in search_keyword
    soup = get_soup_retry(url)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\*\parseAM.py", line 21, in get_soup_retry
    assert page.status_code == 200
           ^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
It worked yeasterday, but gives me that errror rn.
However, when I paste a link for am.co.uk it straggles a bit longer and gives me this error anyways. 

Any ideas why this stopped working?
Thanks ahead!

**Comment by Eugene-Mokrushin** [comment]
Just noticed that it struggled with aw.co.uk because I didnt insert the right link in both places. My bad, sorry!

It still does not work with the prime link tho - .com. Any reasons for this?
